<?php

namespace Modules\Reporting\Support;

class CallReportLabels
{
    public static function relations(): array
    {
        return [
            'program.typeOfProgram:id,name',
            'organization:id,name',
            'productOwner:id,name,surname,email',
            'currentStatusHistory.status:id,name',
            'callCriteria.criterionTranslations',
            'callTranslations.language',
            'applications',
            'applications.team.members:id,name,surname,email',
            'applications.mentorships.mentor:id,name,surname,email',
            'applications.kpis',
            'applications.outputs',
            'applications.milestones',
            'commission.members.user:id,name,surname,email',
            'commissionCompanyRep.user:id,name,surname,email',
        ];
    }

    public static function get(string $lang): array
    {
        return $lang === 'en' ? [
            'title'            => 'Final Project Report',
            'generated'        => 'Call #:id | Generated:',
            'basic_info'       => 'BASIC INFORMATION',
            'call_name'        => 'Call Name',
            'program'          => 'Program',
            'partner'          => 'Partner / Company',
            'product_owner'    => 'Product Owner',
            'deadline'         => 'Application Deadline',
            'project_start'    => 'Project Start',
            'project_end'      => 'Project End',
            'budget'           => 'Budget',
            'status'           => 'Current Status',
            'description'      => 'PROJECT DESCRIPTION',
            'team'             => 'EXECUTING TEAM',
            'team_name'        => 'Team Name',
            'no_team'          => 'No team assigned.',
            'no_members'       => 'No members.',
            'name'             => 'Name',
            'email'            => 'Email',
            'mentor'           => 'MENTOR',
            'no_mentor'        => 'No mentor assigned.',
            'commission'       => 'COMMISSION',
            'commission_name'  => 'Commission Name',
            'company_rep'      => 'Company Representative',
            'no_commission'    => 'No commission assigned.',
            'kpi'              => 'KPI METRICS',
            'metric'           => 'Metric',
            'target'           => 'Target',
            'actual'           => 'Actual',
            'achievement'      => 'Achievement',
            'no_kpi'           => 'No KPIs entered.',
            'outputs'          => 'PROJECT OUTPUTS',
            'output'           => 'Output',
            'type'             => 'Type',
            'planned_delivery' => 'Planned Delivery',
            'actual_delivery'  => 'Actual Delivery',
            'no_outputs'       => 'No outputs entered.',
            'milestones'       => 'PROJECT MILESTONES',
            'milestone_name'   => 'Name',
            'deadline_col'     => 'Deadline',
            'milestone_deadline' => 'Deadline',
            'milestone_status' => 'Status',
            'milestone_comment' => 'Comment',
            'comment'          => 'Comment',
            'no_milestones'    => 'No milestones entered.',
            'no_application'   => 'No approved application exists for this call.',
            'criteria'         => 'EVALUATION CRITERIA',
            'criterion'        => 'Criterion',
            'weight'           => 'Weight',
            'no_criteria'      => 'No criteria.',
        ] : [
            'title'            => 'Záverečný projektový report',
            'generated'        => 'Výzva #:id | Vygenerované:',
            'basic_info'       => 'ZÁKLADNÉ ÚDAJE',
            'call_name'        => 'Názov výzvy',
            'program'          => 'Program',
            'partner'          => 'Partner / Firma',
            'product_owner'    => 'Product Owner',
            'deadline'         => 'Deadline prihlášok',
            'project_start'    => 'Začiatok projektu',
            'project_end'      => 'Koniec projektu',
            'budget'           => 'Rozpočet',
            'status'           => 'Aktuálny stav',
            'description'      => 'POPIS ZADANIA',
            'team'             => 'REALIZUJÚCI TÍM',
            'team_name'        => 'Názov tímu',
            'no_team'          => 'Tím nebol pridelený.',
            'no_members'       => 'Žiadni členovia.',
            'name'             => 'Meno',
            'email'            => 'Email',
            'mentor'           => 'MENTOR',
            'no_mentor'        => 'Mentor nebol pridelený.',
            'commission'       => 'KOMISIA',
            'commission_name'  => 'Názov komisie',
            'company_rep'      => 'Zástupca firmy',
            'no_commission'    => 'Žiadna komisia nebola pridelená.',
            'kpi'              => 'KPI METRIKY',
            'metric'           => 'Metrika',
            'target'           => 'Cieľ',
            'actual'           => 'Skutočnosť',
            'achievement'      => 'Plnenie',
            'no_kpi'           => 'Žiadne KPI neboli zadané.',
            'outputs'          => 'PROJEKTOVÉ VÝSTUPY',
            'output'           => 'Výstup',
            'type'             => 'Typ',
            'planned_delivery' => 'Plánované odovzdanie',
            'actual_delivery'  => 'Skutočné odovzdanie',
            'no_outputs'       => 'Žiadne výstupy neboli zadané.',
            'milestones'       => 'PROJEKTOVÉ MÍĽNIKY',
            'milestone_name'   => 'Názov',
            'deadline_col'     => 'Deadline',
            'milestone_deadline' => 'Deadline',
            'milestone_status' => 'Stav',
            'milestone_comment' => 'Komentár',
            'comment'          => 'Komentár',
            'no_milestones'    => 'Žiadne míľniky neboli zadané.',
            'no_application'   => 'K tejto výzve neexistuje schválená prihláška.',
            'criteria'         => 'HODNOTIACE KRITÉRIÁ',
            'criterion'        => 'Kritérium',
            'weight'           => 'Váha',
            'no_criteria'      => 'Žiadne kritériá.',
        ];
    }
}
